### ISSUE TITLE
Windows and Android Studio - issue with libgg.so and libxp.so

### ISSUE THREAD

**Issue by nilstk** [Fitbit/golden-gate#29]
Hi development team,

I'm unsure if my issue is related to the missing support of Windows. Nevertheless, I'd like to notify you about it.

After downloading the project and importing it to Android Studio for APK compilation, I received the following error about a missing library:

Task :GoldenGateBindings:externalNativeBuildDebug FAILED
Build xp_x86
ninja: Entering directory `C:\tmp\gg\golden-gate\platform\android\goldengate\GoldenGateBindings\.cxx\cmake\debug\x86'
ninja: error: '../../../../../../../../xp/build/cmake/android/x86/libgg.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libxp.so', missing and no known rule to make it

Any idea on how to fix that?

**Comment by nilstk** [comment]
Side note: On Linux it is the same issue. I had the hope it is a Windows issue initially.

Build command failed.
Error while executing process /home/nils/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/nils/Schreibtisch/golden-gate/platform/android/goldengate/GoldenGateBindings/.cxx/cmake/debug/armeabi-v7a xp}
ninja: Entering directory `/home/nils/Schreibtisch/golden-gate/platform/android/goldengate/GoldenGateBindings/.cxx/cmake/debug/armeabi-v7a'

ninja: error: '../../../../../../../../xp/build/cmake/android/armeabi-v7a/libgg.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libxp.so', missing and no known rule to make it

**Comment by Moes81** [comment]
Having the same issue on MacOS with Android Studio 4.2
I followed all steps described in "Getting Started" and "Platform Android". The only thing I changed was updating the two references to the specific NDK version. No other changes. 
I have all the CMAKE versions avalable and the conda `gg` environment is active. Anymore ideas what to check?

**Comment by barbibulle** [comment]
Yes, sorry about that. I will update the documentation to avoid the confusion in the future.
